---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets
  namespace: default
spec:
  encryptedData:
    MONGO_URI: AgCRETy0czoZ4wVkNEcej/c1e4mQqLjRneASJGX4GW5KjxigfTTKM3oxmNJHDiihZdkn2SmxtCXyQNEhv8aItK9bZmnEUgLBwHl0JjE7ZW9AJRn18WMdCzDVe4Tn6Ru/iQGfKaCy2xj4zjl+XCDF4oc3fX/W22ahrFq65XHybi+dJUsKMRpRr4WdJAn/gFwTFKvWKUVnU74hiI/ITGUbGENvs0VBREFcIpWpYDd0yJHGMowpY8RnJXQqnBb9skfRuDcHeZ1EIPxc2nzux0vUlRaNZT9XYaM4Kk4v9m2ImdWeW2XTvvXVzQmGmPsN1xXnnnPBWec82cy+0gtCaxKcs7nLax7VicFQUd0a8xDP7BWe/jqgGCXE4YlFZFwi1xRg2rEoebCpLo0n6TixdpNiBdK21PkmRPp/Fy40d84vcJIAhO9BZH6JnM9wDRuojlEKHN0CqfTCipHPFLwSxJ5F0BOxWxtJjt5d2VmyDVFjQWLfCEJSHoIxZQ5oJpb3p8tcoio3fg6guV7U02mNxLiJ8q84sFunSB+FjG8A63Tl84Rw420fPIlgxvXwmPr6vBcYvA3m8qdkbMczx5j4DH8gp/S3NDaVR6vOoix35vX2FVXLzL4Y8Afj8MXw1yuiVAVMNxl8j9I/9nx3yo/bWAvwpRIpcN+kBQ1cBSeewpYgfomlS8qbml/gLDRW0mMfq9BnOGTKSCgYdZjCwr2+mOqfjAuIlRiG+VZekOahaDV8e1gowtRzNgeAy5uHJosmhjJ0y7CVMDdCSxjAWJo0jI2GWCpYgMmZug==
  template:
    metadata:
      name: backend-secrets
      namespace: default