apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: mongo
  replicas: 2
  PodManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      service: mongo-service
      terminationGracePeriodSeconds: 10
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: mongo
              topologyKey: topology.kubernetes.io/zone
      containers:
        - name: mongo
          image: mongo:6
          ports:
            - containerPort: 27017
          envFrom:
            - secretRef:
                name: mongo-secrets
  volumeClaimTemplates:
    - metadata:
        name: mongo-pvc
      spec:
        accessModes: ["ReadWriteOncePod"]
        storageClassName: "mongo-storage"
        resources:
          requests:
            storage: 5Gi
